Vagrant.configure("2") do |config|
  config.vm.define "node-1" do |node1|
    node1.vm.box = "ubuntu/focal64"
    node1.vm.network :private_network, ip: "11.0.0.10"
    node1.vm.hostname = "node-1"
    node1.vm.network :forwarded_port, guest: 22, host: 3122, id: "ssh"
    node1.ssh.port = 3122
    node1.vm.synced_folder "../../yquake2-bot", "/yquake2-bot"
    node1.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "hosts"
    ansible.playbook = "server_setup_lxd.yml"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3",
      }
    end
  end
  config.vm.define "node-2" do |node2|
    node2.vm.box = "ubuntu/focal64"
    node2.vm.network :private_network, ip: "11.0.0.20"
    node2.vm.hostname = "node-2"
    node2.vm.network :forwarded_port, guest: 22, host: 3222, id: "ssh"
    node2.ssh.port = 3222
    node2.vm.synced_folder "../../yquake2-bot", "/yquake2-bot"
    node2.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "hosts"
      ansible.playbook = "server_setup_lxd.yml"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3",
      }
    end
  end
  config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
end
