---
- hosts: coordinator
  vars:
    container_enumeration:
      - 1
      - 2
      - 3
      - 4
  tasks:
   - name: install prereq snap
     apt:
       name: snapd
       state: latest
   - name: install core snap
     snap:
       name: core
       state: latest
   - name: install core18 snap
     snap:
       name: core18
       state: latest
   - name: install lxd
     snap:
       name: lxd
       state: latest
   - name: initialize lxd cluster - coordinator
     command: cat setup_coordinator.yml | lxd init --preseed
     when: inventory_hostname == node-1  
   - name: initialize lxd cluster - joining nodes
     command: cat setup_node.yml | lxd init --preseed
     when: inventory_hostname != node-1
   - name: initialize lxc network
     command: lxc network create main
   - name: initialize lxc containers
     command: lxc launch images:ubuntu/18.04 container_{{ inventory_hostname }}_{{ item }}
     loop: "{{ container_enumeration }}"
   - name: initialize lxc containers
     command: lxc network attach main container_{{ inventory_hostname }}_{{ item }} eth0
     loop: "{{ container_enumeration }}"
   - name: setup lxc containers
     command: lxc exec --cwd /home/ container_{{ inventory_hostname }}_{{ item }} -- apt-get -y install cmatrix
     loop: "{{ container_enumeration }}"
